id: P005593
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:05:30.276673
source_metadata:
  id: bdr:W29237
  title: མི་གཞིའི་སྙིང་སྟོབས
  author: ''
  volumes:
    8cb3f272201d4aad8fee6d289f656dc2:
      image_group_id: I5546
      title: ''
      volume_number: 1
      total_pages: 290
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
