id: I8639E6D1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T09:38:15+00:00'
last_modified: '2022-06-08T05:09:27.743550+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29237
  title: མི་གཞིའི་སྙིང་སྟོབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '7372':
      image_group_id: I5546
      title: ''
      total_pages: 290
      order: 1
      base_file: 7372.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
